-- Newdryve Ops Portal — board & field configuration seed
-- Transcribed verbatim from the functional spec. Re-runnable (idempotent).

-- Boards ---------------------------------------------------------------------
insert into public.ops_boards (id, module, name, description, stages, position) values
('instructors','customer_outreach','Instructor Pipeline',
  'ADI-qualified driving instructors being recruited onto the platform. Supply side and current bottleneck.',
  array['Not contacted','Contacted','Replied','Interested','Demo sent','Onboarding','Active','Not interested','Dormant'],1),
('learners','customer_outreach','Learner Pipeline',
  'Demand-side acquisition: individual learners, university channels and partner-sourced candidates.',
  array['Lead','Waitlist','Contacted','Signed up','Booked first lesson','Active','Lapsed'],2),
('partnerships','customer_outreach','Partnerships',
  'Organisational channels that supply learners or instructors at volume.',
  array['Identified','Contacted','In conversation','Meeting booked','Agreed','Live','Declined'],3),
('creators','marketing_outreach','Creator & UGC Pipeline',
  'Individual creators and influencers approached for user-generated content and promotion.',
  array['Identified','Contacted','Negotiating','Agreed','Content in progress','Delivered','Published','Declined','Fell through'],4),
('press','marketing_outreach','Press & Media',
  'Journalists, publications and podcasts. Coverage opportunities.',
  array['Identified','Pitched','In conversation','Interview scheduled','Published','No response','Declined'],5),
('campaigns','marketing_outreach','Campaigns',
  'Marketing campaigns and channel experiments, spend tracked against outcome.',
  array['Planned','Live','Paused','Complete'],6),
('pipeline','investor_outreach','Funding Pipeline',
  'All funders, current and prospective.',
  array['Researching','Applied','In review','Meeting / pitch scheduled','Pitched','Diligence','Offer','Accepted','Rejected','Passed','Dormant'],7),
('contacts','investor_outreach','Investor Contacts',
  'Individual investors, panellists and mentors. Warm relationships to maintain for future rounds.',
  array['Met','Connected','Warm','Actively engaged','Cold'],8),
('obligations','investor_outreach','Funding Obligations',
  'Conditions and reporting duties attached to funding already received. Missing these can trigger repayment.',
  array['Upcoming','In progress','Complete','Overdue'],9)
on conflict (id) do update set
  module = excluded.module, name = excluded.name, description = excluded.description,
  stages = excluded.stages, position = excluded.position;

-- Fields ---------------------------------------------------------------------
-- Clear then re-insert so the config always matches the spec exactly.
delete from public.ops_fields;

insert into public.ops_fields (board_id, key, label, type, options, required, is_sensitive, note, position) values
-- instructors
('instructors','business_name','Business name','text',null,true,false,null,1),
('instructors','contact_name','Contact name','text',null,false,false,null,2),
('instructors','mobile','Mobile','text',null,false,true,'Personal data under UK GDPR. Treat as sensitive.',3),
('instructors','email','Email','email',null,false,true,null,4),
('instructors','website','Website','url',null,false,false,null,5),
('instructors','city','City','text',null,false,false,'default: Norwich',6),
('instructors','source','Source','select','["Outscraper","Referral","In person","Facebook group","Inbound","ADINJC","Test centre","Other"]',false,false,null,7),
('instructors','referred_by','Referred by','text',null,false,false,'Which existing instructor referred them. Powers the referral/champion model.',8),
('instructors','stage','Stage','stage',null,true,false,null,9),
('instructors','channel','Channel','select','["WhatsApp","Phone","Email","In person","Social"]',false,false,null,10),
('instructors','date_first_contacted','Date first contacted','date',null,false,false,null,11),
('instructors','date_last_touch','Date last touch','date',null,false,false,null,12),
('instructors','next_action','Next action','text',null,false,false,null,13),
('instructors','next_action_date','Next action date','date',null,false,false,null,14),
('instructors','network_size','Network size','number',null,false,false,'How many other instructors they could bring. Identifies champions.',15),
('instructors','is_champion','Champion','boolean',null,false,false,'Founding champion who actively refers others.',16),
('instructors','subscription_status','Subscription status','select','["None","Free founding member","Trial","Paying","Churned"]',false,false,null,17),
('instructors','owner','Owner','founder_ref',null,false,false,null,18),
('instructors','notes','Notes','longtext',null,false,false,null,19),
-- learners
('learners','name','Name','text',null,true,false,null,1),
('learners','email','Email','email',null,false,true,null,2),
('learners','phone','Phone','text',null,false,true,null,3),
('learners','city','City','text',null,false,false,'default: Norwich',4),
('learners','source','Source','select','["Website waitlist","UEA / Students Union","Freshers fair","Recruitment agency","Instagram","Referral","Instructor referral","Other"]',false,false,null,5),
('learners','stage','Stage','stage',null,true,false,null,6),
('learners','assigned_instructor','Assigned instructor','text',null,false,false,null,7),
('learners','date_added','Date added','date',null,false,false,null,8),
('learners','next_action','Next action','text',null,false,false,null,9),
('learners','next_action_date','Next action date','date',null,false,false,null,10),
('learners','owner','Owner','founder_ref',null,false,false,null,11),
('learners','notes','Notes','longtext',null,false,false,null,12),
-- partnerships
('partnerships','organisation','Organisation','text',null,true,false,null,1),
('partnerships','contact_name','Contact name','text',null,false,false,null,2),
('partnerships','contact_role','Contact role','text',null,false,false,null,3),
('partnerships','email','Email','email',null,false,true,null,4),
('partnerships','phone','Phone','text',null,false,true,null,5),
('partnerships','partnership_type','Partnership type','select','["University / SU","Recruitment agency","Driving school","ADI training provider","Corporate","Other"]',false,false,null,6),
('partnerships','value_proposition','Value proposition','longtext',null,false,false,'What is in it for them specifically.',7),
('partnerships','stage','Stage','stage',null,true,false,null,8),
('partnerships','next_action','Next action','text',null,false,false,null,9),
('partnerships','next_action_date','Next action date','date',null,false,false,null,10),
('partnerships','owner','Owner','founder_ref',null,false,false,null,11),
('partnerships','notes','Notes','longtext',null,false,false,null,12),
-- creators
('creators','creator_name','Creator name','text',null,true,false,null,1),
('creators','handle','Handle','text',null,false,false,null,2),
('creators','platform','Platform','select','["Instagram","TikTok","YouTube","X","LinkedIn","Other"]',false,false,null,3),
('creators','profile_url','Profile URL','url',null,false,false,null,4),
('creators','follower_count','Follower count','number',null,false,false,null,5),
('creators','niche','Niche','select','["Driving / learner","Student / university","Local Norwich","Lifestyle","Other"]',false,false,null,6),
('creators','stage','Stage','stage',null,true,false,null,7),
('creators','agreed_fee','Agreed fee','currency',null,false,false,'GBP. Log the agreed figure to prevent renegotiation disputes.',8),
('creators','fee_paid','Fee paid','boolean',null,false,false,null,9),
('creators','deliverable','Deliverable','text',null,false,false,'What exactly they agreed to produce.',10),
('creators','deadline','Deadline','date',null,false,false,null,11),
('creators','content_url','Content URL','url',null,false,false,null,12),
('creators','performance_notes','Performance notes','longtext',null,false,false,'Reach, engagement, signups attributed.',13),
('creators','owner','Owner','founder_ref',null,false,false,null,14),
('creators','notes','Notes','longtext',null,false,false,null,15),
-- press
('press','outlet','Outlet','text',null,true,false,null,1),
('press','journalist_name','Journalist name','text',null,false,false,null,2),
('press','email','Email','email',null,false,true,null,3),
('press','beat','Beat','text',null,false,false,null,4),
('press','stage','Stage','stage',null,true,false,null,5),
('press','angle_pitched','Angle pitched','longtext',null,false,false,null,6),
('press','date_pitched','Date pitched','date',null,false,false,null,7),
('press','publication_date','Publication date','date',null,false,false,null,8),
('press','article_url','Article URL','url',null,false,false,null,9),
('press','next_action','Next action','text',null,false,false,null,10),
('press','next_action_date','Next action date','date',null,false,false,null,11),
('press','owner','Owner','founder_ref',null,false,false,null,12),
('press','notes','Notes','longtext',null,false,false,null,13),
-- campaigns
('campaigns','campaign_name','Campaign name','text',null,true,false,null,1),
('campaigns','channel','Channel','select','["Instagram","TikTok","Facebook groups","Google","Print / flyers","In person / events","Email","Other"]',false,false,null,2),
('campaigns','audience','Audience','select','["Instructors","Learners","Both"]',false,false,null,3),
('campaigns','stage','Stage','stage',null,true,false,null,4),
('campaigns','budget','Budget','currency',null,false,false,null,5),
('campaigns','spend_to_date','Spend to date','currency',null,false,false,null,6),
('campaigns','grant_funded','Grant funded','boolean',null,false,false,'Flag if paid from the UEA Grow It grant. Grant spend is restricted to the funded Project scope.',7),
('campaigns','start_date','Start date','date',null,false,false,null,8),
('campaigns','end_date','End date','date',null,false,false,null,9),
('campaigns','signups_attributed','Signups attributed','number',null,false,false,null,10),
('campaigns','owner','Owner','founder_ref',null,false,false,null,11),
('campaigns','notes','Notes','longtext',null,false,false,null,12),
-- pipeline (investors)
('pipeline','entity','Entity','text',null,true,false,'Fund, accelerator, grant body or angel name.',1),
('pipeline','type','Type','select','["Grant","Accelerator","Angel","Angel network","VC","Co-investment fund","Competition","Other"]',false,false,null,2),
('pipeline','contact_name','Contact name','text',null,false,false,null,3),
('pipeline','contact_role','Contact role','text',null,false,false,null,4),
('pipeline','email','Email','email',null,false,true,null,5),
('pipeline','stage','Stage','stage',null,true,false,null,6),
('pipeline','amount_sought','Amount sought','currency',null,false,false,null,7),
('pipeline','amount_offered','Amount offered','currency',null,false,false,null,8),
('pipeline','dilutive','Dilutive','boolean',null,false,false,'Whether equity is given up. Grants are non-dilutive.',9),
('pipeline','equity_percent','Equity %','number',null,false,false,null,10),
('pipeline','valuation','Valuation','currency',null,false,false,null,11),
('pipeline','application_deadline','Application deadline','date',null,false,false,null,12),
('pipeline','pitch_date','Pitch date','date',null,false,false,null,13),
('pipeline','decision_date','Decision date','date',null,false,false,null,14),
('pipeline','outcome','Outcome','longtext',null,false,false,null,15),
('pipeline','feedback_received','Feedback received','longtext',null,false,false,'Capture panel questions and objections verbatim. These recur across future pitches.',16),
('pipeline','next_action','Next action','text',null,false,false,null,17),
('pipeline','next_action_date','Next action date','date',null,false,false,null,18),
('pipeline','owner','Owner','founder_ref',null,false,false,null,19),
('pipeline','notes','Notes','longtext',null,false,false,null,20),
-- contacts (investors)
('contacts','name','Name','text',null,true,false,null,1),
('contacts','firm','Firm','text',null,false,false,null,2),
('contacts','role','Role','text',null,false,false,null,3),
('contacts','linkedin_url','LinkedIn URL','url',null,false,false,null,4),
('contacts','email','Email','email',null,false,true,null,5),
('contacts','met_where','Met where','text',null,false,false,'e.g. UEA Enterprise Fund panel, 9 July 2026.',6),
('contacts','stage','Stage','stage',null,true,false,null,7),
('contacts','interest_level','Interest level','select','["Unknown","Low","Medium","High"]',false,false,null,8),
('contacts','last_contact_date','Last contact date','date',null,false,false,null,9),
('contacts','follow_up_due','Follow up due','date',null,false,false,null,10),
('contacts','owner','Owner','founder_ref',null,false,false,null,11),
('contacts','notes','Notes','longtext',null,false,false,null,12),
-- obligations (investors)
('obligations','funder','Funder','text',null,true,false,null,1),
('obligations','obligation','Obligation','longtext',null,true,false,null,2),
('obligations','obligation_type','Obligation type','select','["Reporting","Meeting / engagement","Spend restriction","Signature / return of document","Other"]',false,false,null,3),
('obligations','due_date','Due date','date',null,true,false,null,4),
('obligations','recurring','Recurring','select','["One-off","Quarterly","Annual"]',false,false,null,5),
('obligations','stage','Stage','stage',null,true,false,null,6),
('obligations','owner','Owner','founder_ref',null,false,false,null,7),
('obligations','notes','Notes','longtext',null,false,false,null,8);
